name: Bump version

on:
  workflow_dispatch:
    inputs:
      pkgver:
        description: 'The pkgver to bump'
        required: true
        type: string
      pkgrel:
        description: 'The pkgrel to bump'
        required: true
        type: number
        default: 1
jobs:
  bump_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Update PKGBUILD version
        uses: heyhusen/archlinux-package-action@v2
        with:
          pkgver: ${{ inputs.pkgver }}
          pkgrel: ${{ inputs.pkgrel }}
          flags: ''
          srcinfo: true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: bump version to ${{ inputs.pkgver }}"
          title: "chore: bump version to ${{ inputs.pkgver }}"
          body: "Update package version to ${{ inputs.pkgver }}"
          branch: "bump-version-${{ inputs.pkgver }}"
          delete-branch: true
